Project1-Optimize-Prime/project-one-v1.1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project1-Optimize-Prime/project-one-v1.1/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <label>Mail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1-Optimize-Prime/project-one-v1.1/force-app/main/default/objects/Mail__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Shows the information for package.</description>
    <inlineHelpText>Where the item goes.</inlineHelpText>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Project1-Optimize-Prime/project-one-v1.1/force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>On Route</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1-Optimize-Prime/project-one-v1.1/force-app/main/default/objects/Mail__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1-Optimize-Prime/project-one-v1.1/force-app/main/default/objects/Mail__c/fields/Package_Value__c.field-meta.xml
<CustomField>
    <fullName>Package_Value__c</fullName>
    <label>Package Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Project1-Optimize-Prime/project-one-v1.1/force-app/main/default/objects/Mail__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1-Optimize-Prime/project-one-v1.1/force-app/main/default/classes/MailDisplayControllerTest.cls
@isTest
public with sharing class MailDisplayControllerTest {
    @TestSetup
    private static void CreateMail(){
        Mail__c mailObj = new Mail__c();
        Address__c custAddr = new Address__c();
        
        mailObj.Delivery_Status__c = 'Processing';
        mailObj.Package_Value__c = 2500.50;
        mailObj.Width__c = 15;
        mailObj.Height__c = 20;
        mailObj.Length__c = 30;
        
        mailObj.Address__c = '2598 Summer Wind Dr';
        custAddr.Name = mailObj.Id;
        
        insert mailObj;
    }
    
    @isTest
    private static void genMailListTest(){
        MailDisplayController mailDisConTest = new MailDisplayController();
        
        mailDisConTest.genMailList();
        list<Mail__c> mailObjList = [SELECT Delivery_Status__c FROM Mail__c];
        
        System.assertEquals(1, mailObjList.Size());
        System.debug(mailObjList.Size());
    }
}